#!/usr/bin/env bash
# Derive the app's version build settings from `version` under [workspace.package] in the root
# Cargo.toml, so the app, the engine and the CLI always share one version.
#
# Usage:
#   apps/macos/scripts/set-version.sh                 print MARKETING_VERSION=... and
#                                                     CURRENT_PROJECT_VERSION=... lines, ready to
#                                                     pass to xcodebuild as build settings
#   apps/macos/scripts/set-version.sh --version       print the version only
#   apps/macos/scripts/set-version.sh --xcconfig FILE write the same settings as an xcconfig file
#
# Info.plist reads both settings: CFBundleShortVersionString is MARKETING_VERSION and
# CFBundleVersion is CURRENT_PROJECT_VERSION.
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/../../.." && pwd)"
MANIFEST="$REPO_ROOT/Cargo.toml"

die() { printf 'error: %s\n' "$*" >&2; exit 1; }

# The first `version = "..."` after the [workspace.package] header and before the next table.
version="$(awk '
  /^\[/ { in_pkg = ($0 == "[workspace.package]"); next }
  in_pkg && /^version[[:space:]]*=/ {
    sub(/^version[[:space:]]*=[[:space:]]*"/, ""); sub(/".*$/, ""); print; exit
  }
' "$MANIFEST")"
[[ -n "$version" ]] || die "no version under [workspace.package] in $MANIFEST"
[[ "$version" =~ ^[0-9]+\.[0-9]+\.[0-9]+(-[0-9A-Za-z.-]+)?$ ]] || die "version '$version' is not MAJOR.MINOR.PATCH[-PRERELEASE]"

# CFBundleVersion must be dot-separated integers, so the prerelease suffix is dropped. Sparkle
# compares this value, and the appcast only offers stable releases, so a prerelease and its final
# release sharing it is harmless.
build="${version%%-*}"

settings="MARKETING_VERSION=$version
CURRENT_PROJECT_VERSION=$build"

case "${1:-}" in
  "") printf '%s\n' "$settings" ;;
  --version) printf '%s\n' "$version" ;;
  --xcconfig)
    [[ -n "${2:-}" ]] || die "--xcconfig needs a file path"
    mkdir -p "$(dirname "$2")"
    printf '// Generated by apps/macos/scripts/set-version.sh from Cargo.toml.\n%s\n' \
      "${settings//=/ = }" >"$2"
    ;;
  *) die "unknown argument: $1" ;;
esac
